application:
  microservice-configuration:
    hazelcast:
      discovery-mechanism: "{cipher}a5346838c5821ef9e6f812cccb4c2da48f267f506151672f0af6a63c4e49ad6b"
      lite-member:
        cluster-members: "conversationlogger"
        instance-port-padding: 5701
  microservice-role:
    aggregator: true
    raw-data: true
  service-time-configuration:
    service-time1-lower-bound: 0
    service-time1-upper-bound: 10
    service-time2-lower-bound: 10
    service-time2-upper-bound: 20
    service-time3-lower-bound: 20
    service-time3-upper-bound: 30
    service-time4-lower-bound: 30
    service-time4-upper-bound: 60
  task-executor-properties:
    core-size: 4
    maximum-size: 6
    queue-capacity: 1000000
cron-job:
  initialize-agent-aggregation-15-min-cron: "0 6/15 * * * ?"
  initialize-agent-session-aggregation-15-min-cron: "0 4/15 * * * ?"
  initialize-agent-sub-type-aggregation-15-min-cron: "0 8/15 * * * ?"
  initialize-queue-aggregation-15-min-cron: "0 7/15 * * * ?"
eureka:
  client:
    service-url:
      defaultZone: "{cipher}844024d628754a0049fc200aeb8b32f3613ce610cce3ffce41e82cbe12ee4cc46169dfeec4506c824d30bd1a056e3339945e69d7377da0cecb3162427d70d8fc"
jhipster:
  security:
    oauth2:
      audience:
      - "account"
      - "api://default"
      - "sistas-chatbot"
      - "sistas-eva"
      - "sistas-voice"
kafka:
  agentMessageTopic: "AGENT_MESSAGE_TOPIC"
  bootstrap-servers: "localhost:9092"
  callMessageTopic: "CALL_MESSAGE_TOPIC"
  consumer:
    auto.offset.reset: "latest"
    group.id: "conversation-logger"
  different-group-id-consumer:
    auto.offset.reset: "latest"
    group.id: "conversation-logger-${spring.application.instance-id:${random.value}}"
  fromConversationLoggerToMediaProcessorTopic: "FROM_CONVERSATION_LOGGER_TO_MEDIA_PROCESSOR_TOPIC"
  fromMediaProcessorToConversationLoggerTopic: "FROM_MEDIA_PROCESSOR_TO_CONVERSATION_LOGGER_TOPIC"
  generalMessageTopic: "GENERAL_MESSAGE_TOPIC"
  sendAckTimeoutSeconds: 10
  sendRetryDelaySeconds: 2
  sendRetrySchedulerThreads: 8
  topics:
    number-of-partitions: 1
    replication-factor: 1
logging:
  level:
    ROOT: "DEBUG"
not-ready-reason:
  default-provider: "sisphone"
server:
  port: 26083
spring:
  cloud.stream.kafka.binder.brokers: "localhost:9092"
  datasource:
    hikari:
      maximum-pool-size: 500
      minimum-idle: 50
    password: "{cipher}9cdbcbe6249ad1ae8ed392289a193f7a805b3d2d587400caa4a49417aba9986b74cd08e8b4e8e0ba936e29029fd872d8"
    url: "jdbc:sqlserver://localhost:1433;database=sis-voice;encrypt=true;trustServerCertificate=true"
    username: "{cipher}28949e4d08f1770acae02a2ac37a3f31443991685799d8dd438ea3ddaa6f1256c9034015d2b926f9ed58f09eb63bc496"
  security:
    oauth2:
      client:
        provider.oidc.issuer-uri: "keycloak-url"
        registration:
          oidc:
            client-id: "sistas-cc-solution"
            client-secret: "{cipher}7446ca9b425c26b1a1fa4b82ebacac8185fc44753e4d3d3ad22fe0bca2b59e58"
user-data-config:
  cron: "0 0 * * * ?"
  instance-name: "USER_DATA"
  profile: "prod"
