application:
  microservice-configuration:
    hazelcast:
      discovery-mechanism: "{cipher}b93be7fd9f6221b754e8592b89d9ed86f54acd166f9e345bded5161233c5a243"
      lite-member:
        cluster-members: "conversationlogger"
        instance-port-padding: 5701
  microservice-role:
    aggregator: true
    raw-data: true
  service-time-configuration:
    service-time1-lower-bound: 0
    service-time1-upper-bound: 10
    service-time2-lower-bound: 10
    service-time2-upper-bound: 20
    service-time3-lower-bound: 20
    service-time3-upper-bound: 30
    service-time4-lower-bound: 30
    service-time4-upper-bound: 60
  task-executor-properties:
    core-size: 4
    maximum-size: 6
    queue-capacity: 1000000
cron-job:
  initialize-agent-aggregation-15-min-cron: "0 6/15 * * * ?"
  initialize-agent-session-aggregation-15-min-cron: "0 4/15 * * * ?"
  initialize-agent-sub-type-aggregation-15-min-cron: "0 8/15 * * * ?"
  initialize-queue-aggregation-15-min-cron: "0 7/15 * * * ?"
eureka:
  client:
    service-url:
      defaultZone: "{cipher}fcd2ab0aee94147d485a088e1c4c007a62af2708ea2785a82bb8827ace38fa9139aed12df0022bece9460102d6a1aa79dba91a6e6f6d76bc5ed64a91d7f5f226"
jhipster:
  security:
    oauth2:
      audience:
      - "account"
      - "api://default"
      - "sistas-chatbot"
      - "sistas-eva"
      - "sistas-voice"
kafka:
  agentMessageTopic: "AGENT_MESSAGE_TOPIC"
  bootstrap-servers: "localhost:9092"
  callMessageTopic: "CALL_MESSAGE_TOPIC"
  consumer:
    auto.offset.reset: "latest"
    group.id: "conversation-logger"
  different-group-id-consumer:
    auto.offset.reset: "latest"
    group.id: "conversation-logger-${spring.application.instance-id:${random.value}}"
  fromConversationLoggerToMediaProcessorTopic: "FROM_CONVERSATION_LOGGER_TO_MEDIA_PROCESSOR_TOPIC"
  fromMediaProcessorToConversationLoggerTopic: "FROM_MEDIA_PROCESSOR_TO_CONVERSATION_LOGGER_TOPIC"
  generalMessageTopic: "GENERAL_MESSAGE_TOPIC"
  sendAckTimeoutSeconds: 10
  sendRetryDelaySeconds: 2
  sendRetrySchedulerThreads: 8
  topics:
    number-of-partitions: 1
    replication-factor: 1
logging:
  level:
    ROOT: "DEBUG"
    com.sistas.cc.conversation.logger: "DEBUG"
    org:
      hibernate:
        ASQL.selam: "TRACE"
        SQL: "DEBUG"
    tech.jhipster: "DEBUG"
not-ready-reason:
  default-provider: "sisphone"
server:
  port: 26083
spring:
  cloud.stream.kafka.binder.brokers: "localhost:9092"
  datasource:
    hikari:
      maximum-pool-size: 500
      minimum-idle: 50
    password: "{cipher}f9b5551a251c2d7ecf7dc2cf8521315af56221d94a54a053037ff3b1e9f1b34bf0cc2a3682b8f0e21f71d508d2799b64"
    url: "jdbc:sqlserver://localhost:1433;database=sis-voice;encrypt=true;trustServerCertificate=true"
    username: "{cipher}97b4f656bc3094c3d34484784f25e82d0b5797d13e3b4113e5116e6697349e5155d3575c65b2f347d89f1144c82a322a"
  security:
    oauth2:
      client:
        provider.oidc.issuer-uri: "keycloak-url"
        registration:
          oidc:
            client-id: "sistas-cc-solution"
            client-secret: "{cipher}8617630f067bc52b20a718e07d1437f58f14c71dedd1fde62a1a6d752aa5ff88"
user-data-config:
  cron: "0 0 * * * ?"
  instance-name: "USER_DATA"
  profile: "prod"
