application:
  microservice-configuration:
    hazelcast:
      discovery-mechanism: "{cipher}0908137bd85bebccfd08ea3b69785ea872ae97f53bfa005e1a320b7b9bae94ee"
      lite-member:
        cluster-members: "conversationlogger"
        instance-port-padding: 5701
  microservice-role:
    aggregator: true
    raw-data: true
  service-time-configuration:
    service-time1-lower-bound: 0
    service-time1-upper-bound: 10
    service-time2-lower-bound: 10
    service-time2-upper-bound: 20
    service-time3-lower-bound: 20
    service-time3-upper-bound: 30
    service-time4-lower-bound: 30
    service-time4-upper-bound: 60
  task-executor-properties:
    core-size: 4
    maximum-size: 6
    queue-capacity: 1000000
cron-job:
  initialize-agent-aggregation-15-min-cron: "0 6/15 * * * ?"
  initialize-agent-session-aggregation-15-min-cron: "0 4/15 * * * ?"
  initialize-agent-sub-type-aggregation-15-min-cron: "0 8/15 * * * ?"
  initialize-queue-aggregation-15-min-cron: "0 7/15 * * * ?"
eureka:
  client:
    service-url:
      defaultZone: "{cipher}3a495f8e6f33c1d086aa4e80669f4d396367c57430bbb9f0ac92630484a855a356334ea2e2afb563711f501d2c042a13bb2ddd7bbb726d5a77202dbd3dcf5710"
jhipster:
  security:
    oauth2:
      audience:
      - "account"
      - "api://default"
      - "sistas-chatbot"
      - "sistas-eva"
      - "sistas-voice"
kafka:
  agentMessageTopic: "AGENT_MESSAGE_TOPIC"
  bootstrap-servers: "localhost:9092"
  callMessageTopic: "CALL_MESSAGE_TOPIC"
  consumer:
    auto.offset.reset: "latest"
    group.id: "conversation-logger"
  different-group-id-consumer:
    auto.offset.reset: "latest"
    group.id: "conversation-logger-${spring.application.instance-id:${random.value}}"
  fromConversationLoggerToMediaProcessorTopic: "FROM_CONVERSATION_LOGGER_TO_MEDIA_PROCESSOR_TOPIC"
  fromMediaProcessorToConversationLoggerTopic: "FROM_MEDIA_PROCESSOR_TO_CONVERSATION_LOGGER_TOPIC"
  generalMessageTopic: "GENERAL_MESSAGE_TOPIC"
  sendAckTimeoutSeconds: 10
  sendRetryDelaySeconds: 2
  sendRetrySchedulerThreads: 8
  topics:
    number-of-partitions: 1
    replication-factor: 1
logging:
  level:
    ROOT: "DEBUG"
    com.sistas.cc.conversation.logger: "DEBUG"
    org:
      hibernate:
        ASQL.selam: "TRACE"
        SQL: "DEBUG"
    tech.jhipster: "DEBUG"
not-ready-reason:
  default-provider: "sisphone"
server:
  port: 26083
spring:
  cloud.stream.kafka.binder.brokers: "localhost:9092"
  datasource:
    hikari:
      maximum-pool-size: 500
      minimum-idle: 50
    password: "{cipher}6ee89efbde80aea7258f4ec7a4cf3dc59a8bfbdbc7e240a6e891fe92925280bd587bee2d08720be010d1bcba6e85f47f"
    url: "jdbc:sqlserver://localhost:1433;database=sis-voice;encrypt=true;trustServerCertificate=true"
    username: "{cipher}e750c28b0df917ebb0a82ecc32d7c6b0ced59adee8aed603b50e98557b361ae617ecea692b7c9d9a87a5507f2c85bea4"
  security:
    oauth2:
      client:
        provider.oidc.issuer-uri: "keycloak-url"
        registration:
          oidc:
            client-id: "sistas-cc-solution"
            client-secret: "{cipher}6d19481fc74f72e9771816388a76ca7d8a69e0d165dd7bd2697d0926c989a61f"
user-data-config:
  cron: "0 0 * * * ?"
  instance-name: "USER_DATA"
  profile: "prod"
