userData1: "PopUpField"
userData10: "PreviousReasonCode"
userData11: "PreviousReasonText"
userData12: "deviceType"
userData2: "tcknencrypeted"
userData3: "vipmessage"
userData4: "retired"
userData5: "survey"
userData6: "ReasonCode"
userData7: "ReasonText"
userData8: "GlobalConnId"
userData9: "releasingParty"
